# Operaciones con DataFrames

In [ ]:
import pandas as pd
df = pd.read_csv('data/grades.csv', index_col=0)
df

                PIA  SAA  MIA   SBD   BDA
Alan Turing     7.0  9.0  7.0  10.0   9.9
Claude Shannon  6.5  8.0  6.0   9.0   6.9
John McCarthy   6.5  8.5  6.0   9.0   7.8
Marvin Minsky   5.7  8.0  7.0   9.0  10.0

## Gestión de columnas

In [ ]:
df.insert(0, 'ID', ['11222333A', '22333222B', '33222333C', '44333222D'])  # inserta una columna ID en la posición 0
df.insert(1, 'Age', [23, 23, 36, 36])  # inserta una columna Age en la posición 1
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0

In [ ]:
# O simplemente podemos añadir una columna al final
df['Other'] = [1, 1, 1, 1]  # si la columna no existe, la crea; si existe, la sobrescribe
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  Other
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9      1
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9      1
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8      1
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0      1

In [ ]:
# Crea una columna nueva con las notas de PIA normalizadas
df['PIA_norm'] = (df['PIA'] - df['PIA'].min()) / (df['PIA'].max() - df['PIA'].min())
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  Other  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9      1  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9      1  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8      1  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0      1  0.000000

In [ ]:
df.drop('Other', axis=1)  # devuelve un DataFrame nuevo sin la columna 'Other', pero no modifica el DataFrame original
# df  # si mostramos el DataFrame original, vemos que la columna 'Other' sigue ahí

                       ID  Age  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0  0.000000

```drop``` tiene el parámetro ```axis```, que por defecto vale 0, lo que indica que se borrarán filas. Si quieres borrar columnas, tienes que especificar ```axis=1```, o su equivalente ```axis='columns'```.

In [ ]:
df.drop('Other', axis=1, inplace=True)  # borra la columna 'Other' del DataFrame original
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0  0.000000

> [!IMPORTANT]
> Con `inplace=True`, el método modifica el propio DataFrame y devuelve `None`, en lugar de devolver un DataFrame nuevo. Como devuelve `None`, no se puede encadenar con otros métodos. Los desarrolladores de pandas lo desaconsejan: han aceptado una propuesta, [PDEP-8](https://pandas.pydata.org/pdeps/0008-inplace-methods-in-pandas.html), para eliminarlo de la mayoría de los métodos, como `drop`, `rename` y `set_index`, porque asignar el resultado hace lo mismo. Asigna el resultado en su lugar: `df = df.drop(columns='Other')`.

También puedes usar los parámetros ```columns``` e ```index``` para borrar columnas o filas, respectivamente.

In [ ]:
df.drop(columns='Age')  # devuelve otro DataFrame sin 'Age'

                       ID  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D  5.7  8.0  7.0   9.0  10.0  0.000000

In [ ]:
df.drop(columns=['PIA_norm', 'Age'])  # devuelve otro DataFrame sin 'PIA_norm' ni 'Age'

                       ID  PIA  SAA  MIA   SBD   BDA
Alan Turing     11222333A  7.0  9.0  7.0  10.0   9.9
Claude Shannon  22333222B  6.5  8.0  6.0   9.0   6.9
John McCarthy   33222333C  6.5  8.5  6.0   9.0   7.8
Marvin Minsky   44333222D  5.7  8.0  7.0   9.0  10.0

### Usar `assign` para añadir columnas

El método `assign` ofrece una forma más limpia de añadir columnas calculadas, sobre todo al encadenar métodos. A diferencia de la asignación directa (`df['col'] = ...`), `assign` devuelve un DataFrame nuevo sin modificar el original.

In [ ]:
# assign devuelve un DataFrame nuevo con la columna nueva
df.assign(PIA_doubled=df['PIA'] * 2)

,ID,Age,PIA,SAA,MIA,SBD,BDA,PIA_norm,PIA_doubled
Alan Turing,11222333A,23,7.0,9.0,7.0,10.0,9.9,1.000000,14.0
Claude Shannon,22333222B,23,6.5,8.0,6.0,9.0,6.9,0.615385,13.0
John McCarthy,33222333C,36,6.5,8.5,6.0,9.0,7.8,0.615385,13.0
Marvin Minsky,44333222D,36,5.7,8.0,7.0,9.0,10.0,0.000000,11.4

In [ ]:
# Usar lambda permite hacer referencia a columnas creadas en la misma llamada a assign
df.assign(
    average=lambda x: (x['PIA'] + x['SAA'] + x['MIA']) / 3,
    passed=lambda x: x['average'] >= 5  # Usa la columna que se acaba de crear arriba
)

,ID,Age,PIA,SAA,MIA,SBD,BDA,PIA_norm,average,passed
Alan Turing,11222333A,23,7.0,9.0,7.0,10.0,9.9,1.000000,7.666667,True
Claude Shannon,22333222B,23,6.5,8.0,6.0,9.0,6.9,0.615385,6.833333,True
John McCarthy,33222333C,36,6.5,8.5,6.0,9.0,7.8,0.615385,7.000000,True
Marvin Minsky,44333222D,36,5.7,8.0,7.0,9.0,10.0,0.000000,6.900000,True

> **Consejo:** `assign` es especialmente potente combinado con `groupby` y `transform` para añadir columnas calculadas a partir de estadísticos de grupo. Consulta el notebook **[Transformaciones de DataFrames](pandas_transformations.ipynb)** para ver ejemplos avanzados.

## Gestión de filas

In [ ]:
# df.at['Alan Turing'] # Daría error; at solo sirve para acceder a una celda concreta
df.loc['Alan Turing'] # Obtiene una fila completa como Series

ID          11222333A
Age                23
PIA               7.0
SAA               9.0
MIA               7.0
SBD              10.0
BDA               9.9
PIA_norm          1.0
Name: Alan Turing, dtype: object

In [ ]:
import numpy as np
df.loc['Arthur Samuel'] = ['55444333E', 25, 8, 8.0, 7.0, 9.0, 6.0, np.nan] # Añade un alumno nuevo
# Como la columna PIA_norm necesita antes la columna PIA, no podemos añadir el valor de PIA_norm
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0  0.000000
Arthur Samuel   55444333E   25  8.0  8.0  7.0   9.0   6.0       NaN

El valor de la columna "PIA_norm" tiene que calcularse procesando toda la columna "PIA" y asignando después el resultado a la columna "PIA_norm". Por eso he optado por asignar la **constante** ```np.nan``` **(Not A Number)** al añadir una fila nueva: para indicar que de momento no tenemos esa información (tendremos que recalcular los valores normalizados).

In [ ]:
df.drop('Arthur Samuel') # Las filas se pueden borrar como las columnas (en este caso no uso inplace=True porque no quiero modificar el DataFrame original)
#df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0  0.000000

## Acceder a los elementos

In [ ]:
print(df.at['Alan Turing','PIA']) # Accede a una celda concreta de forma más eficiente que loc
print(df.loc['Alan Turing','PIA'])
print(df.loc['Alan Turing'].at['PIA'])  # loc devuelve una Series con los datos de la fila, así que podemos usar at para acceder a un elemento concreto de esa Series
print(df['PIA']['Alan Turing'])
print(df['PIA'].at['Alan Turing'])
print(df.iat[0,2])  # Acceso por posición entera: primera fila, tercera columna
print(df.iloc[0,2])

7.0
7.0
7.0
7.0
7.0
7.0
7.0

`.at` lee o escribe un valor por sus etiquetas, y es la forma más rápida de hacerlo; `.loc` también selecciona por etiquetas, pero además puede devolver una fila, una columna o un slice. `.iat` e `.iloc` hacen lo mismo por posición.

La tercera y la cuarta línea son *indexación encadenada*: una primera selección devuelve una Series, y una segunda coge el valor de ella. Leer así funciona, pero es más lento y menos claro que un único `.at` o `.loc`. Escribir así no funciona en absoluto, como muestran las celdas siguientes.

In [ ]:
df.at['Alan Turing', 'PIA'] = 10 # Modifica un valor usando el índice de la fila y el nombre de la columna
df.loc['Alan Turing', 'PIA'] = 10 # Equivale a lo anterior
df

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23   6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Arthur Samuel   55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN

In [ ]:
df.iloc[1, 2] = 0 # Modifica una nota usando posiciones
df

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23   0.0  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Arthur Samuel   55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN

Desde pandas 3.0, toda selección se comporta como una copia (*copy-on-write*), así que un valor asignado mediante indexación encadenada cambia esa copia temporal y nunca `df`. pandas lo avisa con un `ChainedAssignmentError`, y el valor se queda como estaba. Para asignar, selecciona con un único `.loc` o `.at`, como arriba:

In [ ]:
df['PIA']['Alan Turing'] = 0  # asignación encadenada: pandas avisa, y df no cambia
df.loc['Alan Turing', 'PIA']

/tmp/ipykernel_1857969/3643558758.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df['PIA']['Alan Turing'] = 0  # chained assignment: pandas warns, and df doesn't change

np.float64(10.0)

Cuando las etiquetas son enteros, `.loc` e `.iloc` dan resultados distintos: `.loc[1, 1]` es la fila y la columna con *etiqueta* 1, e `.iloc[1, 1]` la segunda fila y la segunda columna.

In [ ]:
dict_num_keys1 = {1: 'one', 2: 'two', 3: 'three'}
dict_num_keys2 = {1: 'I', 2: 'II', 3: 'III'}
dict_num_keys3 = {1: 'first', 2: 'second', 3: 'third'}

df_ints_as_keys = pd.DataFrame({1: dict_num_keys1, 2: dict_num_keys2, 3: dict_num_keys3})
print(df_ints_as_keys.iloc[1, 1])
print(df_ints_as_keys.loc[1, 1])

II
one

## Acceder a partes de un DataFrame

In [ ]:
df[['ID']]  # devuelve un DataFrame con la columna ID

                       ID
Alan Turing     11222333A
Claude Shannon  22333222B
John McCarthy   33222333C
Marvin Minsky   44333222D
Arthur Samuel   55444333E

In [ ]:
df['ID']  # devuelve una Series con la columna ID

Alan Turing       11222333A
Claude Shannon    22333222B
John McCarthy     33222333C
Marvin Minsky     44333222D
Arthur Samuel     55444333E
Name: ID, dtype: str

In [ ]:
df.ID  # equivale a lo anterior

Alan Turing       11222333A
Claude Shannon    22333222B
John McCarthy     33222333C
Marvin Minsky     44333222D
Arthur Samuel     55444333E
Name: ID, dtype: str

In [ ]:
df[['ID', 'PIA']]  # devuelve un DataFrame con las columnas ID y PIA

                       ID   PIA
Alan Turing     11222333A  10.0
Claude Shannon  22333222B   0.0
John McCarthy   33222333C   6.5
Marvin Minsky   44333222D   5.7
Arthur Samuel   55444333E   8.0

In [ ]:
df.loc['Alan Turing', ['PIA','SAA','MIA']] # Accede a una fila y varias columnas

PIA    10.0
SAA     9.0
MIA     7.0
Name: Alan Turing, dtype: float64

## Slicing

In [ ]:
df.loc[:, 'PIA':'MIA'] # Devuelve un DataFrame con todas las filas y las columnas PIA, SAA y MIA

                 PIA  SAA  MIA
Alan Turing     10.0  9.0  7.0
Claude Shannon   0.0  8.0  6.0
John McCarthy    6.5  8.5  6.0
Marvin Minsky    5.7  8.0  7.0
Arthur Samuel    8.0  8.0  7.0

In [ ]:
df.iloc[:3, 0:3] # Devuelve un DataFrame con las filas anteriores a la fila 3, y las columnas 0, 1 y 2

                       ID  Age   PIA
Alan Turing     11222333A   23  10.0
Claude Shannon  22333222B   23   0.0
John McCarthy   33222333C   36   6.5

In [ ]:
df.loc[:'Marvin Minsky'] # Devuelve un DataFrame con las filas hasta Marvin Minsky, incluida

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23   0.0  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000

## Crear un DataFrame nuevo aplicando filtros

In [ ]:
# Alumnos que aprobaron PIA y SAA
df[(df['PIA'] >= 5) & (df['SAA'] >= 5)]

                      ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing    11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
John McCarthy  33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky  44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Arthur Samuel  55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN

In [ ]:
df[(df['PIA'] >= 5) | (df['SAA'] >= 5)] [['PIA','SAA','MIA']] # Alumnos que aprobaron PIA o SAA, con sus notas en esos módulos y en MIA

                 PIA  SAA  MIA
Alan Turing     10.0  9.0  7.0
Claude Shannon   0.0  8.0  6.0
John McCarthy    6.5  8.5  6.0
Marvin Minsky    5.7  8.0  7.0
Arthur Samuel    8.0  8.0  7.0

In [ ]:
passed_pia_and_saa = df[(df['PIA'] >= 5) & (df['SAA'] >= 5)]  # alumnos que aprobaron PIA y SAA
passed_pia_and_saa = passed_pia_and_saa.set_index('ID')  # identificados por su ID
passed_pia_and_saa[['PIA', 'SAA', 'MIA']]  # con sus notas en esos módulos y en MIA

            PIA  SAA  MIA
ID
11222333A  10.0  9.0  7.0
33222333C   6.5  8.5  6.0
44333222D   5.7  8.0  7.0
55444333E   8.0  8.0  7.0

In [ ]:
df[(df['PIA'] >= 5) & (df['SAA'] >= 5)].set_index('ID')[['PIA', 'SAA', 'MIA']]  # lo mismo, en una sola línea

            PIA  SAA  MIA
ID
11222333A  10.0  9.0  7.0
33222333C   6.5  8.5  6.0
44333222D   5.7  8.0  7.0
55444333E   8.0  8.0  7.0

## Ordenar

In [ ]:
df.sort_values('PIA', ascending=False) # Ordena el DataFrame por la columna PIA en orden descendente

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Arthur Samuel   55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Claude Shannon  22333222B   23   0.0  8.0  6.0   9.0   6.9  0.615385

In [ ]:
df.sort_values(by=['PIA', 'SAA', 'MIA'], ascending=False) # Ordena el DataFrame por las columnas PIA, SAA y MIA (en ese orden de prioridad)

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Arthur Samuel   55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Claude Shannon  22333222B   23   0.0  8.0  6.0   9.0   6.9  0.615385

## Agregaciones básicas

Pandas ofrece métodos sencillos para calcular estadísticos sobre columnas o filas.

In [ ]:
df['PIA'].mean() # Media de la columna PIA

np.float64(6.04)

In [ ]:
df.sum() # Suma de cada columna

ID          11222333A22333222B33222333C44333222D55444333E
Age                                                   143
PIA                                                  30.2
SAA                                                  41.5
MIA                                                  33.0
SBD                                                  46.0
BDA                                                  40.6
PIA_norm                                         2.230769
dtype: object

In [ ]:
df.loc[:, ['PIA', 'SAA', 'MIA', 'BDA', 'SBD']].mean(axis='columns')  # nota media de cada alumno en los cinco módulos
# axis='columns' (o axis=1) calcula la media a lo largo de las columnas, una vez por cada fila

Alan Turing       9.18
Claude Shannon    5.98
John McCarthy     7.56
Marvin Minsky     7.94
Arthur Samuel     7.60
dtype: float64

In [ ]:
df['SBD'].value_counts() # Devuelve el número de veces que aparece cada valor en la columna SBD
# cuatro alumnos sacaron un 9 en SBD y uno sacó un 10

SBD
9.0     4
10.0    1
Name: count, dtype: int64

In [ ]:
df.isnull() # Devuelve un DataFrame con True en las celdas que contienen NaN y False en las que no
df.isna()  # Equivale a lo anterior («not available», no disponible)

                   ID    Age    PIA    SAA    MIA    SBD    BDA  PIA_norm
Alan Turing     False  False  False  False  False  False  False     False
Claude Shannon  False  False  False  False  False  False  False     False
John McCarthy   False  False  False  False  False  False  False     False
Marvin Minsky   False  False  False  False  False  False  False     False
Arthur Samuel   False  False  False  False  False  False  False      True

In [ ]:
df.isnull().sum() # Devuelve el número de valores nulos de cada columna

ID          0
Age         0
PIA         0
SAA         0
MIA         0
SBD         0
BDA         0
PIA_norm    1
dtype: int64

Para las **operaciones de agrupación** (`groupby`, `agg`, `transform` y `apply` por grupos), las **transformaciones elemento a elemento** (`map`, `apply`, `transform`) y el **remodelado de datos** (`melt`, `pivot`, `pivot_table`), consulta el notebook **[Transformaciones y remodelado de DataFrames](pandas_transformations.ipynb)**.

## Recursos adicionales

- https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html
- https://www.listendata.com/2017/12/python-pandas-tutorial.html