# DataFrame Operations

In [ ]:
import pandas as pd
df = pd.read_csv('data/grades.csv', index_col=0)
df

                PIA  SAA  MIA   SBD   BDA
Alan Turing     7.0  9.0  7.0  10.0   9.9
Claude Shannon  6.5  8.0  6.0   9.0   6.9
John McCarthy   6.5  8.5  6.0   9.0   7.8
Marvin Minsky   5.7  8.0  7.0   9.0  10.0

## Column management

In [ ]:
df.insert(0, 'ID', ['11222333A', '22333222B', '33222333C', '44333222D'])  # insert an ID column at position 0
df.insert(1, 'Age', [23, 23, 36, 36])  # insert an Age column at position 1
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0

In [ ]:
# Or we can simply add a column at the end
df['Other'] = [1, 1, 1, 1]  # if the column doesn't exist, it creates it; if it exists, it overwrites it
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  Other
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9      1
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9      1
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8      1
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0      1

In [ ]:
# Create a new column with normalised PIA grades
df['PIA_norm'] = (df['PIA'] - df['PIA'].min()) / (df['PIA'].max() - df['PIA'].min())
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  Other  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9      1  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9      1  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8      1  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0      1  0.000000

In [ ]:
df.drop('Other', axis=1)  # returns a new DataFrame without the 'Other' column, but doesn't modify the original DataFrame
# df  # if we show the original DataFrame, we see that the 'Other' column is still there

                       ID  Age  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0  0.000000

```drop``` has the ```axis``` parameter which defaults to 0, indicating that rows will be deleted. If you want to delete columns, you must specify ```axis=1```, or its equivalent ```axis='columns'```.

In [ ]:
df.drop('Other', axis=1, inplace=True)  # deletes the 'Other' column from the original DataFrame
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0  0.000000

> [!IMPORTANT]
> With `inplace=True`, the method changes the DataFrame itself and returns `None`, instead of returning a new DataFrame. Because it returns `None`, it can't be chained with other methods. The pandas developers discourage it: they have accepted a proposal, [PDEP-8](https://pandas.pydata.org/pdeps/0008-inplace-methods-in-pandas.html), to remove it from most methods, such as `drop`, `rename` and `set_index`, because assigning the result does the same. Assign the result instead: `df = df.drop(columns='Other')`.

You can also use the ```columns``` and ```index``` parameters to delete columns or rows, respectively.

In [ ]:
df.drop(columns='Age')  # returns another DataFrame without 'Age'

                       ID  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D  5.7  8.0  7.0   9.0  10.0  0.000000

In [ ]:
df.drop(columns=['PIA_norm', 'Age'])  # returns another DataFrame without 'PIA_norm' or 'Age'

                       ID  PIA  SAA  MIA   SBD   BDA
Alan Turing     11222333A  7.0  9.0  7.0  10.0   9.9
Claude Shannon  22333222B  6.5  8.0  6.0   9.0   6.9
John McCarthy   33222333C  6.5  8.5  6.0   9.0   7.8
Marvin Minsky   44333222D  5.7  8.0  7.0   9.0  10.0

### Using `assign` for Adding Columns

The `assign` method provides a cleaner way to add computed columns, especially when method chaining. Unlike direct assignment (`df['col'] = ...`), `assign` returns a new DataFrame without modifying the original.

In [ ]:
# assign returns a new DataFrame with the new column
df.assign(PIA_doubled=df['PIA'] * 2)

,ID,Age,PIA,SAA,MIA,SBD,BDA,PIA_norm,PIA_doubled
Alan Turing,11222333A,23,7.0,9.0,7.0,10.0,9.9,1.000000,14.0
Claude Shannon,22333222B,23,6.5,8.0,6.0,9.0,6.9,0.615385,13.0
John McCarthy,33222333C,36,6.5,8.5,6.0,9.0,7.8,0.615385,13.0
Marvin Minsky,44333222D,36,5.7,8.0,7.0,9.0,10.0,0.000000,11.4

In [ ]:
# Using lambda allows referencing columns created in the same assign call
df.assign(
    average=lambda x: (x['PIA'] + x['SAA'] + x['MIA']) / 3,
    passed=lambda x: x['average'] >= 5  # Uses the column just created above
)

,ID,Age,PIA,SAA,MIA,SBD,BDA,PIA_norm,average,passed
Alan Turing,11222333A,23,7.0,9.0,7.0,10.0,9.9,1.000000,7.666667,True
Claude Shannon,22333222B,23,6.5,8.0,6.0,9.0,6.9,0.615385,6.833333,True
John McCarthy,33222333C,36,6.5,8.5,6.0,9.0,7.8,0.615385,7.000000,True
Marvin Minsky,44333222D,36,5.7,8.0,7.0,9.0,10.0,0.000000,6.900000,True

> **Tip:** `assign` is especially powerful when combined with `groupby` and `transform` for adding computed columns based on group statistics. See the **[DataFrame Transformations](pandas_transformations.ipynb)** notebook for advanced examples.

## Row management

In [ ]:
# df.at['Alan Turing'] # Would error; at only works to access a specific cell
df.loc['Alan Turing'] # Retrieve a complete row as a Series

ID          11222333A
Age                23
PIA               7.0
SAA               9.0
MIA               7.0
SBD              10.0
BDA               9.9
PIA_norm          1.0
Name: Alan Turing, dtype: object

In [ ]:
import numpy as np
df.loc['Arthur Samuel'] = ['55444333E', 25, 8, 8.0, 7.0, 9.0, 6.0, np.nan] # Add a new student
# Since the PIA_norm column requires the PIA column first, we cannot add the value of PIA_norm
df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0  0.000000
Arthur Samuel   55444333E   25  8.0  8.0  7.0   9.0   6.0       NaN

The value of the "PIA_norm" column has to be calculated by processing the entire "PIA" column and then assigning the result to the "PIA_norm" column. That's why I chose to assign the **constant** ```np.nan``` **(Not A Number)** when adding a new row: to indicate that we don't have that information for now (we will need to recalculate the normalised values).

In [ ]:
df.drop('Arthur Samuel') # Rows can be deleted like columns (in this case I don't use inplace=True because I don't want to modify the original DataFrame)
#df

                       ID  Age  PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  7.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23  6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36  6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36  5.7  8.0  7.0   9.0  10.0  0.000000

## Accessing elements

In [ ]:
print(df.at['Alan Turing','PIA']) # Access a specific cell more efficiently than loc
print(df.loc['Alan Turing','PIA'])
print(df.loc['Alan Turing'].at['PIA'])  # loc returns a series with the row data, so we can use at to access a specific element of that series
print(df['PIA']['Alan Turing']) 
print(df['PIA'].at['Alan Turing'])
print(df.iat[0,2])  # Access by integer position: first row, third column
print(df.iloc[0,2])

7.0
7.0
7.0
7.0
7.0
7.0
7.0

`.at` reads or writes one value by its labels, and is the fastest way to do it; `.loc` selects by labels too, but can also return a row, a column or a slice. `.iat` and `.iloc` do the same by position.

The third and fourth lines are *chained indexing*: a first selection returns a Series, and a second one picks the value from it. Reading this way works, but it is slower and less clear than a single `.at` or `.loc`. Writing this way doesn't work at all, as the next cells show.

In [ ]:
df.at['Alan Turing', 'PIA'] = 10 # Modify a value using the row index and column name
df.loc['Alan Turing', 'PIA'] = 10 # Equivalent to the above
df

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23   6.5  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Arthur Samuel   55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN

In [ ]:
df.iloc[1, 2] = 0 # Modify a grade using positions
df

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23   0.0  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Arthur Samuel   55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN

Since pandas 3.0, every selection behaves as a copy (*copy-on-write*), so a value assigned through chained indexing changes that temporary copy and never `df`. pandas warns about it with a `ChainedAssignmentError`, and the value stays as it was. To assign, select with a single `.loc` or `.at`, as above:

In [ ]:
df['PIA']['Alan Turing'] = 0  # chained assignment: pandas warns, and df doesn't change
df.loc['Alan Turing', 'PIA']

/tmp/ipykernel_1857969/3643558758.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df['PIA']['Alan Turing'] = 0  # chained assignment: pandas warns, and df doesn't change

np.float64(10.0)

When the labels are integers, `.loc` and `.iloc` give different results: `.loc[1, 1]` is the row and column *labelled* 1, and `.iloc[1, 1]` the second row and the second column.

In [ ]:
dict_num_keys1 = {1: 'one', 2: 'two', 3: 'three'}
dict_num_keys2 = {1: 'I', 2: 'II', 3: 'III'}
dict_num_keys3 = {1: 'first', 2: 'second', 3: 'third'}

df_ints_as_keys = pd.DataFrame({1: dict_num_keys1, 2: dict_num_keys2, 3: dict_num_keys3})
print(df_ints_as_keys.iloc[1, 1])
print(df_ints_as_keys.loc[1, 1])

II
one

## Accessing parts of a DataFrame

In [ ]:
df[['ID']]  # returns a DataFrame with the ID column

                       ID
Alan Turing     11222333A
Claude Shannon  22333222B
John McCarthy   33222333C
Marvin Minsky   44333222D
Arthur Samuel   55444333E

In [ ]:
df['ID']  # returns a Series with the ID column

Alan Turing       11222333A
Claude Shannon    22333222B
John McCarthy     33222333C
Marvin Minsky     44333222D
Arthur Samuel     55444333E
Name: ID, dtype: str

In [ ]:
df.ID  # equivalent to the above

Alan Turing       11222333A
Claude Shannon    22333222B
John McCarthy     33222333C
Marvin Minsky     44333222D
Arthur Samuel     55444333E
Name: ID, dtype: str

In [ ]:
df[['ID', 'PIA']]  # returns a DataFrame with the ID and PIA columns

                       ID   PIA
Alan Turing     11222333A  10.0
Claude Shannon  22333222B   0.0
John McCarthy   33222333C   6.5
Marvin Minsky   44333222D   5.7
Arthur Samuel   55444333E   8.0

In [ ]:
df.loc['Alan Turing', ['PIA','SAA','MIA']] # Access a row and several columns

PIA    10.0
SAA     9.0
MIA     7.0
Name: Alan Turing, dtype: float64

## Slicing

In [ ]:
df.loc[:, 'PIA':'MIA'] # Returns a DataFrame of all rows with columns PIA, SAA and MIA

                 PIA  SAA  MIA
Alan Turing     10.0  9.0  7.0
Claude Shannon   0.0  8.0  6.0
John McCarthy    6.5  8.5  6.0
Marvin Minsky    5.7  8.0  7.0
Arthur Samuel    8.0  8.0  7.0

In [ ]:
df.iloc[:3, 0:3] # Returns a DataFrame of rows before row 3, with columns 0, 1 and 2

                       ID  Age   PIA
Alan Turing     11222333A   23  10.0
Claude Shannon  22333222B   23   0.0
John McCarthy   33222333C   36   6.5

In [ ]:
df.loc[:'Marvin Minsky'] # Returns a DataFrame with rows up to and including Marvin Minsky

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Claude Shannon  22333222B   23   0.0  8.0  6.0   9.0   6.9  0.615385
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000

## Creating a new DataFrame by applying filters

In [ ]:
# Students who passed PIA and SAA
df[(df['PIA'] >= 5) & (df['SAA'] >= 5)]

                      ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing    11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
John McCarthy  33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky  44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Arthur Samuel  55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN

In [ ]:
df[(df['PIA'] >= 5) | (df['SAA'] >= 5)] [['PIA','SAA','MIA']] # Students who passed PIA or SAA with their grades in those modules and in MIA

                 PIA  SAA  MIA
Alan Turing     10.0  9.0  7.0
Claude Shannon   0.0  8.0  6.0
John McCarthy    6.5  8.5  6.0
Marvin Minsky    5.7  8.0  7.0
Arthur Samuel    8.0  8.0  7.0

In [ ]:
passed_pia_and_saa = df[(df['PIA'] >= 5) & (df['SAA'] >= 5)]  # students who passed PIA and SAA
passed_pia_and_saa = passed_pia_and_saa.set_index('ID')  # identified by their ID
passed_pia_and_saa[['PIA', 'SAA', 'MIA']]  # with their grades in those modules and in MIA

            PIA  SAA  MIA
ID
11222333A  10.0  9.0  7.0
33222333C   6.5  8.5  6.0
44333222D   5.7  8.0  7.0
55444333E   8.0  8.0  7.0

In [ ]:
df[(df['PIA'] >= 5) & (df['SAA'] >= 5)].set_index('ID')[['PIA', 'SAA', 'MIA']]  # the same, in a single line

            PIA  SAA  MIA
ID
11222333A  10.0  9.0  7.0
33222333C   6.5  8.5  6.0
44333222D   5.7  8.0  7.0
55444333E   8.0  8.0  7.0

## Sorting

In [ ]:
df.sort_values('PIA', ascending=False) # Sorts the DataFrame by the PIA column in descending order

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Arthur Samuel   55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Claude Shannon  22333222B   23   0.0  8.0  6.0   9.0   6.9  0.615385

In [ ]:
df.sort_values(by=['PIA', 'SAA', 'MIA'], ascending=False) # Sorts the DataFrame by columns PIA, SAA and MIA (in that order of priority)

                       ID  Age   PIA  SAA  MIA   SBD   BDA  PIA_norm
Alan Turing     11222333A   23  10.0  9.0  7.0  10.0   9.9  1.000000
Arthur Samuel   55444333E   25   8.0  8.0  7.0   9.0   6.0       NaN
John McCarthy   33222333C   36   6.5  8.5  6.0   9.0   7.8  0.615385
Marvin Minsky   44333222D   36   5.7  8.0  7.0   9.0  10.0  0.000000
Claude Shannon  22333222B   23   0.0  8.0  6.0   9.0   6.9  0.615385

## Basic Aggregations

Pandas provides simple methods for computing statistics over columns or rows.

In [ ]:
df['PIA'].mean() # Mean of the PIA column

np.float64(6.04)

In [ ]:
df.sum() # Sum of each column

ID          11222333A22333222B33222333C44333222D55444333E
Age                                                   143
PIA                                                  30.2
SAA                                                  41.5
MIA                                                  33.0
SBD                                                  46.0
BDA                                                  40.6
PIA_norm                                         2.230769
dtype: object

In [ ]:
df.loc[:, ['PIA', 'SAA', 'MIA', 'BDA', 'SBD']].mean(axis='columns')  # average grade of each student in the five modules
# axis='columns' (or axis=1) computes the mean across the columns, once for each row

Alan Turing       9.18
Claude Shannon    5.98
John McCarthy     7.56
Marvin Minsky     7.94
Arthur Samuel     7.60
dtype: float64

In [ ]:
df['SBD'].value_counts() # Returns the number of times each value appears in the SBD column
# four students got a 9 in SBD and one got a 10

SBD
9.0     4
10.0    1
Name: count, dtype: int64

In [ ]:
df.isnull() # Returns a DataFrame with True in cells that contain NaN and False in those that don't
df.isna()  # Equivalent to the above ("not available")

                   ID    Age    PIA    SAA    MIA    SBD    BDA  PIA_norm
Alan Turing     False  False  False  False  False  False  False     False
Claude Shannon  False  False  False  False  False  False  False     False
John McCarthy   False  False  False  False  False  False  False     False
Marvin Minsky   False  False  False  False  False  False  False     False
Arthur Samuel   False  False  False  False  False  False  False      True

In [ ]:
df.isnull().sum() # Returns the number of null values in each column

ID          0
Age         0
PIA         0
SAA         0
MIA         0
SBD         0
BDA         0
PIA_norm    1
dtype: int64

For **grouping operations** (`groupby`, `agg`, group-wise `transform` and `apply`), **element-wise transformations** (`map`, `apply`, `transform`), and **data reshaping** (`melt`, `pivot`, `pivot_table`), see the **[DataFrame Transformations and Reshaping](pandas_transformations.ipynb)** notebook.

## Additional resources

- https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html
- https://www.listendata.com/2017/12/python-pandas-tutorial.html